/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzy;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class Halaman_Home extends javax.swing.JFrame {

    /**
     * Creates new form Form_utama
     */
    public Halaman_Home() {
        initComponents();
        layar_tengah();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Tambah_PDRB = new javax.swing.JMenuItem();
        hitung_coba = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Klasifikasi = new javax.swing.JMenuItem();
        kelola_data_klasifikasi = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klasifikasi Pembangunan Wilayah");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Provinsi Jawa Barat Dengan Metode Fuzzy-Klassen");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihann/baruuuuuu.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Aplikasi Klasifikasi Pembangunan Wilayah ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Selamat Datang ..!\n\nAplikasi Ini menggunakan Metode Fuzzy-Klassen sebagai\nmetode klasifikasinya.\nMetode ini ditemukan oleh Munandar dan Wardoyo pada tahun 2015.\nMetode ini menggabungkan Fuzzy-System dengan Tipologi Klassen\nuntuk menghaslkan keluaran berupa \nKuadran Pembangunan Suatu Wilayah.\n\nFuzzy-Klassen menggunakan variabel :\n1. Nilai PDRB tahunan Kabupaten, \n2. Laju Pertumbuhan (RD) Kabupaten, \n3. Nilai Kontribusi (RC) Kabupaten, \n4. Nilai PDRB tahunan Provinsi, \n5. Laju Pertumbuhan (RD) Provinsi, \n6. Nilai Kontribusi (RC) Provinsi, \n\nFuzzy Klassen diawali dengan Fuzzy sistem, dimana Fuzzy sistem\nmenghitung seluruh variabel sehingga menghasilkan nilai keluaran\nFuzzy-System Defuzzyfikasi Berupa :\n1. RD Defuzzykasi Kabupaten (ri)\n2. RC Fuzzyfikasi Kabupaten (yi)\n3. RD Fuzzyfikasi Provinsi (r)\n4. RC Fuzzyfikasi Kabupaten (y)\n\nSelanjutnya Variabel Defuzzyfikasi tersebut diproses dengan \nAturan Tipologi Klassen sehingga menghasilkan Output Berupa \nKuadran Pembangunan suatu Kota/Wilayah");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihann/zx.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Alur Metode Fuzzy Klassen ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        Tambah_PDRB.setText("Tambah Data PDRB");
        Tambah_PDRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah_PDRBActionPerformed(evt);
            }
        });
        jMenu1.add(Tambah_PDRB);

        hitung_coba.setText("Lihat Data PDRB");
        hitung_coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_cobaActionPerformed(evt);
            }
        });
        jMenu1.add(hitung_coba);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Klasifikasi");

        Klasifikasi.setText("Klasifikasi Kab/Kota");
        Klasifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlasifikasiActionPerformed(evt);
            }
        });
        jMenu2.add(Klasifikasi);

        kelola_data_klasifikasi.setText("Data Klasifikasi");
        kelola_data_klasifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelola_data_klasifikasiActionPerformed(evt);
            }
        });
        jMenu2.add(kelola_data_klasifikasi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void layar_tengah(){
    // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
       
    }
    
    private void Tambah_PDRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah_PDRBActionPerformed
        this.dispose();
        new MenuUtama().show();    
    }//GEN-LAST:event_Tambah_PDRBActionPerformed

    private void hitung_cobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_cobaActionPerformed
      this.dispose();
      new Kelola_PDRB().show();    
    }//GEN-LAST:event_hitung_cobaActionPerformed

    private void KlasifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlasifikasiActionPerformed
     this.dispose();
     new coba().show();    
    }//GEN-LAST:event_KlasifikasiActionPerformed

    private void kelola_data_klasifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelola_data_klasifikasiActionPerformed
     this.dispose();
     new Klasifikasi().show();   
    }//GEN-LAST:event_kelola_data_klasifikasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem Klasifikasi;
    public javax.swing.JMenuItem Tambah_PDRB;
    private javax.swing.JMenuItem hitung_coba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JMenuItem kelola_data_klasifikasi;
    // End of variables declaration//GEN-END:variables
}
