/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzy;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Kelola_PDRB extends javax.swing.JFrame {
private Connection con;
private Statement stat;
private ResultSet res;
    /**
     * Creates new form Kelola_PDRB
     */
    public Kelola_PDRB() {
        initComponents();
        koneksi();
        layar_tengah();
        
        panel_edit.setEnabled(false);
        panel_edit.setVisible(false);
        panel_edit1.setEnabled(false);
        panel_edit1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BORDER = new javax.swing.JPanel();
        ISI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_tahun = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        PANEL_PDRB = new javax.swing.JPanel();
        kab_n = new javax.swing.JScrollPane();
        tbl_prov = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        kab = new javax.swing.JScrollPane();
        tbl_kab = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        panel_edit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_kab = new javax.swing.JTextField();
        txt_pdrb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panel_edit1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_prov = new javax.swing.JTextField();
        txt_pdrb_prov = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Tambah_PDRB = new javax.swing.JMenuItem();
        hitung_coba = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Klasifikasi = new javax.swing.JMenuItem();
        kelola_data_klasifikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data PDRB");

        BORDER.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Input Tahun :");

        txt_tahun.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        proses.setText("Lihat Nilai PDRB");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        PANEL_PDRB.setBackground(new java.awt.Color(255, 255, 255));
        PANEL_PDRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        tbl_prov.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tbl_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_prov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_provMouseClicked(evt);
            }
        });
        kab_n.setViewportView(tbl_prov);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PDRB Kabupaten / Kota Di JAWA BARAT");

        tbl_kab.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tbl_kab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kabMouseClicked(evt);
            }
        });
        kab.setViewportView(tbl_kab);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PDRB Provinsi INDONESIA");

        javax.swing.GroupLayout PANEL_PDRBLayout = new javax.swing.GroupLayout(PANEL_PDRB);
        PANEL_PDRB.setLayout(PANEL_PDRBLayout);
        PANEL_PDRBLayout.setHorizontalGroup(
            PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addComponent(kab, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(kab_n, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_PDRBLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(67, 67, 67))))
        );
        PANEL_PDRBLayout.setVerticalGroup(
            PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kab_n, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                    .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btn_hapus.setText("Hapus data");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        panel_edit.setBackground(new java.awt.Color(255, 255, 255));
        panel_edit.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 2, true));

        jLabel2.setText("Nama Kabupaten");

        jLabel3.setText("Nilai PDRB");

        txt_kab.setEditable(false);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Update Data Kabupaten");

        javax.swing.GroupLayout panel_editLayout = new javax.swing.GroupLayout(panel_edit);
        panel_edit.setLayout(panel_editLayout);
        panel_editLayout.setHorizontalGroup(
            panel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_editLayout.createSequentialGroup()
                .addGroup(panel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(panel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel_editLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addGap(52, 52, 52)
                            .addComponent(txt_pdrb))
                        .addGroup(panel_editLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel5))
                        .addGroup(panel_editLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txt_kab, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_editLayout.setVerticalGroup(
            panel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_editLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_kab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pdrb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panel_edit1.setBackground(new java.awt.Color(255, 255, 255));
        panel_edit1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.green, 2, true));

        jLabel6.setText("Nama Kabupaten");

        jLabel7.setText("Nilai PDRB");

        txt_prov.setEditable(false);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Update Data Provinsi");

        javax.swing.GroupLayout panel_edit1Layout = new javax.swing.GroupLayout(panel_edit1);
        panel_edit1.setLayout(panel_edit1Layout);
        panel_edit1Layout.setHorizontalGroup(
            panel_edit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_edit1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(78, 78, 78))
            .addGroup(panel_edit1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_edit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(panel_edit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel_edit1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(52, 52, 52)
                            .addComponent(txt_pdrb_prov))
                        .addGroup(panel_edit1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panel_edit1Layout.setVerticalGroup(
            panel_edit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_edit1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_edit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_edit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_pdrb_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ISILayout = new javax.swing.GroupLayout(ISI);
        ISI.setLayout(ISILayout);
        ISILayout.setHorizontalGroup(
            ISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL_PDRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ISILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ISILayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(proses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_hapus))
                    .addGroup(ISILayout.createSequentialGroup()
                        .addComponent(panel_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(panel_edit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ISILayout.setVerticalGroup(
            ISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ISILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapus)
                    .addComponent(proses)
                    .addComponent(jLabel1)
                    .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(ISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_edit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(PANEL_PDRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BORDERLayout = new javax.swing.GroupLayout(BORDER);
        BORDER.setLayout(BORDERLayout);
        BORDERLayout.setHorizontalGroup(
            BORDERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BORDERLayout.createSequentialGroup()
                .addComponent(ISI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BORDERLayout.setVerticalGroup(
            BORDERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BORDERLayout.createSequentialGroup()
                .addComponent(ISI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jMenu1.setText("File");

        Tambah_PDRB.setText("Tambah Data PDRB");
        Tambah_PDRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah_PDRBActionPerformed(evt);
            }
        });
        jMenu1.add(Tambah_PDRB);

        hitung_coba.setText("Lihat Data PDRB");
        hitung_coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_cobaActionPerformed(evt);
            }
        });
        jMenu1.add(hitung_coba);

        jMenuItem1.setText("Halaman Utama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Klasifikasi");

        Klasifikasi.setText("Klasifikasi Kab/Kota");
        Klasifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlasifikasiActionPerformed(evt);
            }
        });
        jMenu2.add(Klasifikasi);

        kelola_data_klasifikasi.setText("Data Klasifikasi");
        kelola_data_klasifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelola_data_klasifikasiActionPerformed(evt);
            }
        });
        jMenu2.add(kelola_data_klasifikasi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BORDER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BORDER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void layar_tengah(){
    // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
       
    }
    
    private void koneksi(){
        try {Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/klasifikasi", "root", "");
        stat=con.createStatement();}catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Tidak Terhubung dengan database");        }    }
    
    private void tableshow(){
    int tahun,tahun_n;
    tahun   = Integer.parseInt(txt_tahun.getText());

     DefaultTableModel kb= new DefaultTableModel();
        kb.addColumn("Kabupaten");
        kb.addColumn("PDRB "+tahun+"");
        tbl_kab.setModel(kb);
        
        DefaultTableModel prn= new DefaultTableModel();
        prn.addColumn("Provinsi");
        prn.addColumn("PDRB "+tahun+"");
        tbl_prov.setModel(prn);
        
        try{
            res=stat.executeQuery("SELECT tbl_kabupaten.kabupaten, tbl_kabupaten.pdrb, tbl_kabupaten.tahun FROM tbl_kabupaten WHERE tahun='"+tahun+"'");
            while (res.next()){
            kb.addRow(new Object[]{
            res.getString("kabupaten"),
            res.getString("pdrb")});
            }
        }catch (Exception e){ JOptionPane.showMessageDialog(null, "Data PDRB Kabupaten/ Kota Tahun "+txt_tahun.getText()+" tidak dimukan");}
        
         try{
            res=stat.executeQuery("SELECT tbl_provinsi.provinsi, tbl_provinsi.pdrb, tbl_provinsi.tahun FROM tbl_provinsi WHERE tahun='"+txt_tahun.getText()+"'");
            while (res.next()){
            prn.addRow(new Object[]{
            res.getString("provinsi"),
            res.getString("pdrb")});
            }
        }catch (Exception e){ JOptionPane.showMessageDialog(null, "Data Tahun PDRB Provinsi Tahun "+txt_tahun.getText()+" tidak dimukan");}
        
    
    
    }
    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
       
        if (txt_tahun.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Input Tahun Tidak Boleh Kosong");}
        else{
             panel_edit.setEnabled(true);   
             panel_edit.setVisible(true);
             panel_edit1.setEnabled(true);   
             panel_edit1.setVisible(true);
            tableshow();

}

      
    }//GEN-LAST:event_prosesActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Menghapus data Klasifikasi Tahun "+txt_tahun.getText()+" ???", "Konfirmasi",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0)
       {
        try
         {
            String sql="delete from tbl_kabupaten where tahun='"+txt_tahun.getText()+"'";
            String sql1="delete from tbl_provinsi where tahun='"+txt_tahun.getText()+"'";
            
            PreparedStatement st=con.prepareStatement(sql);
             PreparedStatement sz=con.prepareStatement(sql1);
            st.executeUpdate();
            sz.executeUpdate();
            JOptionPane.showMessageDialog(null, "Hapus Data Sukses");
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Hapus Data Gagal");
        }
       }
       tableshow();
 
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_kabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kabMouseClicked
        txt_kab.setText(tbl_kab.getValueAt(tbl_kab.getSelectedRow(), 0).toString());
        txt_pdrb.setText(tbl_kab.getValueAt(tbl_kab.getSelectedRow(), 1).toString());
        
    }//GEN-LAST:event_tbl_kabMouseClicked

    private void Tambah_PDRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah_PDRBActionPerformed
        this.dispose();
        new MenuUtama().show();
    }//GEN-LAST:event_Tambah_PDRBActionPerformed

    private void KlasifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlasifikasiActionPerformed
        this.dispose();
        new coba().show();
    }//GEN-LAST:event_KlasifikasiActionPerformed

    private void kelola_data_klasifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelola_data_klasifikasiActionPerformed
        this.dispose();
        new Klasifikasi().show();
    }//GEN-LAST:event_kelola_data_klasifikasiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.dispose();
       new Halaman_Home();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void hitung_cobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_cobaActionPerformed
        this.dispose();
        new Kelola_PDRB().show();
    }//GEN-LAST:event_hitung_cobaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
            String sql ="UPDATE tbl_kabupaten SET kabupaten = '"+txt_kab.getText()+"', pdrb = '"+txt_pdrb.getText()+"' WHERE kabupaten = '"+txt_kab.getText()+"' AND tahun = '"+txt_tahun.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil diupdate");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            String sql ="UPDATE tbl_provinsi SET provinsi = '"+txt_prov.getText()+"', pdrb = '"+txt_pdrb_prov.getText()+"' WHERE provinsi = '"+txt_prov.getText()+"' AND tahun = '"+txt_tahun.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil diupdate");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbl_provMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_provMouseClicked
    txt_prov.setText(tbl_prov.getValueAt(tbl_prov.getSelectedRow(), 0).toString());
    txt_pdrb_prov.setText(tbl_prov.getValueAt(tbl_prov.getSelectedRow(), 1).toString());
        
        
    }//GEN-LAST:event_tbl_provMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kelola_PDRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kelola_PDRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kelola_PDRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kelola_PDRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kelola_PDRB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BORDER;
    private javax.swing.JPanel ISI;
    private javax.swing.JMenuItem Klasifikasi;
    private javax.swing.JPanel PANEL_PDRB;
    private javax.swing.JMenuItem Tambah_PDRB;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JMenuItem hitung_coba;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane kab;
    private javax.swing.JScrollPane kab_n;
    private javax.swing.JMenuItem kelola_data_klasifikasi;
    private javax.swing.JPanel panel_edit;
    private javax.swing.JPanel panel_edit1;
    private javax.swing.JButton proses;
    public javax.swing.JTable tbl_kab;
    public javax.swing.JTable tbl_prov;
    private javax.swing.JTextField txt_kab;
    private javax.swing.JTextField txt_pdrb;
    private javax.swing.JTextField txt_pdrb_prov;
    private javax.swing.JTextField txt_prov;
    public javax.swing.JTextField txt_tahun;
    // End of variables declaration//GEN-END:variables
}
