/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzy;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Kelola_PDRB1 extends javax.swing.JFrame {
private Connection con;
private Statement stat;
private ResultSet res;
    /**
     * Creates new form Kelola_PDRB
     */
    public Kelola_PDRB1() {
        initComponents();
        koneksi();
        layar_tengah();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BORDER = new javax.swing.JPanel();
        ISI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_tahun = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        PANEL_PDRB = new javax.swing.JPanel();
        kab_n = new javax.swing.JScrollPane();
        tbl_prov = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        kab = new javax.swing.JScrollPane();
        tbl_kab = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        kelola_data_klasifikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BORDER.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Input Tahun :");

        txt_tahun.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        proses.setText("Lihat Nilai PDRB");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        PANEL_PDRB.setBackground(new java.awt.Color(255, 255, 255));
        PANEL_PDRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        tbl_prov.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tbl_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_prov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_provMouseClicked(evt);
            }
        });
        kab_n.setViewportView(tbl_prov);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PDRB Kabupaten / Kota Di JAWA BARAT");

        tbl_kab.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tbl_kab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kabMouseClicked(evt);
            }
        });
        kab.setViewportView(tbl_kab);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PDRB Provinsi INDONESIA");

        javax.swing.GroupLayout PANEL_PDRBLayout = new javax.swing.GroupLayout(PANEL_PDRB);
        PANEL_PDRB.setLayout(PANEL_PDRBLayout);
        PANEL_PDRBLayout.setHorizontalGroup(
            PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addComponent(kab, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(kab_n, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_PDRBLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(67, 67, 67))))
        );
        PANEL_PDRBLayout.setVerticalGroup(
            PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_PDRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kab_n, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                    .addGroup(PANEL_PDRBLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout ISILayout = new javax.swing.GroupLayout(ISI);
        ISI.setLayout(ISILayout);
        ISILayout.setHorizontalGroup(
            ISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL_PDRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ISILayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(proses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ISILayout.setVerticalGroup(
            ISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ISILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proses)
                    .addComponent(jLabel1)
                    .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PANEL_PDRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BORDERLayout = new javax.swing.GroupLayout(BORDER);
        BORDER.setLayout(BORDERLayout);
        BORDERLayout.setHorizontalGroup(
            BORDERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BORDERLayout.createSequentialGroup()
                .addComponent(ISI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BORDERLayout.setVerticalGroup(
            BORDERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BORDERLayout.createSequentialGroup()
                .addComponent(ISI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Halaman Utama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Klasifikasi");

        kelola_data_klasifikasi.setText("Data Klasifikasi");
        kelola_data_klasifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelola_data_klasifikasiActionPerformed(evt);
            }
        });
        jMenu2.add(kelola_data_klasifikasi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BORDER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BORDER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void layar_tengah(){
    // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
       
    }
    
    private void koneksi(){
        try {Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/klasifikasi", "root", "");
        stat=con.createStatement();}catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Tidak Terhubung dengan database");        }    }
    
    private void tableshow(){
    int tahun,tahun_n;
    tahun   = Integer.parseInt(txt_tahun.getText());

     DefaultTableModel kb= new DefaultTableModel();
        kb.addColumn("Kabupaten");
        kb.addColumn("PDRB "+tahun+"");
        tbl_kab.setModel(kb);
        
        DefaultTableModel prn= new DefaultTableModel();
        prn.addColumn("Provinsi");
        prn.addColumn("PDRB "+tahun+"");
        tbl_prov.setModel(prn);
        
        try{
            res=stat.executeQuery("SELECT tbl_kabupaten.kabupaten, tbl_kabupaten.pdrb, tbl_kabupaten.tahun FROM tbl_kabupaten WHERE tahun='"+tahun+"'");
            while (res.next()){
            kb.addRow(new Object[]{
            res.getString("kabupaten"),
            res.getString("pdrb")});
            }
        }catch (Exception e){ JOptionPane.showMessageDialog(null, "Data PDRB Kabupaten/ Kota Tahun "+txt_tahun.getText()+" tidak dimukan");}
        
         try{
            res=stat.executeQuery("SELECT tbl_provinsi.provinsi, tbl_provinsi.pdrb, tbl_provinsi.tahun FROM tbl_provinsi WHERE tahun='"+txt_tahun.getText()+"'");
            while (res.next()){
            prn.addRow(new Object[]{
            res.getString("provinsi"),
            res.getString("pdrb")});
            }
        }catch (Exception e){ JOptionPane.showMessageDialog(null, "Data Tahun PDRB Provinsi Tahun "+txt_tahun.getText()+" tidak dimukan");}
        
    
    
    }
    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
       
        if (txt_tahun.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Input Tahun Tidak Boleh Kosong");}
        else{
             
            tableshow();

}

      
    }//GEN-LAST:event_prosesActionPerformed

    private void tbl_kabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kabMouseClicked
        
        
    }//GEN-LAST:event_tbl_kabMouseClicked

    private void kelola_data_klasifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelola_data_klasifikasiActionPerformed
        this.dispose();
        new Klasifikasi1().show();
    }//GEN-LAST:event_kelola_data_klasifikasiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.dispose();
       new Halaman_Home1();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tbl_provMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_provMouseClicked
     
        
    }//GEN-LAST:event_tbl_provMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kelola_PDRB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kelola_PDRB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kelola_PDRB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kelola_PDRB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kelola_PDRB1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BORDER;
    private javax.swing.JPanel ISI;
    private javax.swing.JPanel PANEL_PDRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane kab;
    private javax.swing.JScrollPane kab_n;
    private javax.swing.JMenuItem kelola_data_klasifikasi;
    private javax.swing.JButton proses;
    public javax.swing.JTable tbl_kab;
    public javax.swing.JTable tbl_prov;
    public javax.swing.JTextField txt_tahun;
    // End of variables declaration//GEN-END:variables
}
